show_avatars:
  default: false
  description:
    en: Display excerpt avatar.
show_reply_icon:
  default: false
  description:
    en: Display a reply icon before latest post excerpt.
show_topic_excerpt:
  default: false
  description:
    en: Show topic excerpts
single_line:
  default: false
  description:
    en: Apply styling to limit excerpt to a single line.
use_topic_creator_avatar_mobile:
  default: false
  description:
    en: Use the topic creator avatar on mobile instead of latest poster.
